# Generated by Django 5.1.4 on 2025-01-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_remove_product_category_product_color_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
